# Generated by Django 3.1.7 on 2023-07-03 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_medico', '0001_initial'),
        ('medico', '0001_initial'),
        ('informante_atencion', '0001_initial'),
        ('diagnostico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_atencion', models.CharField(blank=True, max_length=50, null=True)),
                ('traslado', models.BooleanField(default=False)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('distrito', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_salida_ambulancia', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada_EESS', models.DateTimeField(blank=True, null=True)),
                ('activate', models.BooleanField(blank=True, default=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=None, null=True)),
                ('user_updated', models.CharField(default=None, max_length=50, null=True)),
                ('id_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico')),
                ('id_informante_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informante_atencion.informanteatencion')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_medico.personalmedico')),
            ],
        ),
    ]
