# Generated by Django 3.1.7 on 2023-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='photo_url',
            field=models.CharField(
                default='https://res.cloudinary.com/ddksrkond/image/upload/v1688411778/default_dfvymc.webp', max_length=255),
        ),
    ]
