# Generated by Django 3.1.7 on 2023-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='desactivate_account',
            field=models.BooleanField(default=True),
        ),
    ]
