# Generated by Django 3.1.7 on 2023-07-03 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformanteAtencion',
            fields=[
                ('id_llamada', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_llamada', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_infor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres_infor', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos_infor', models.CharField(blank=True, max_length=50, null=True)),
                ('dni_infor', models.CharField(blank=True, max_length=20, null=True)),
                ('gen_infor', models.CharField(blank=True, max_length=20, null=True)),
                ('activate', models.BooleanField(blank=True, default=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=None, null=True)),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_medico.personalmedico')),
            ],
        ),
    ]
